/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sql;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Werner
 */
public class Attend extends javax.swing.JPanel {

    /**
     * Creates new form Attend
     */
    public Attend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        stnum = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        counterField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        warningField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        okButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 251, 251));

        jButton1.setBackground(new java.awt.Color(243, 231, 231));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Add new student");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Student number");

        stnum.setBackground(new java.awt.Color(204, 204, 255));
        stnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnumActionPerformed(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        okButton.setText("OK");
        okButton.setBorder(null);
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okButtonMouseExited(evt);
            }
        });
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        counterField.setBackground(new java.awt.Color(204, 204, 255));
        counterField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        counterField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                counterFieldMouseClicked(evt);
            }
        });
        counterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counterFieldActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Days attended");

        warningField.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("50 % warning");

        okButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        okButton1.setText("Cancel");
        okButton1.setBorder(null);
        okButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                okButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                okButton1MouseExited(evt);
            }
        });
        okButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stnum, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(okButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(counterField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(warningField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(okButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stnum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(counterField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warningField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        AddStudent one = new AddStudent();
//        FlowLayout out = new FlowLayout();
//
//        this.removeAll();
//        this.repaint();
//        this.revalidate();
//
//        this.add(one);
//        this.setLayout(out);
//        this.repaint();
//        this.revalidate();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:sqlserver://localhost:1433; databaseName=AttendanceSystem; user=sa; password=XP890";
            Connection con = (Connection) DriverManager.getConnection(url);
            Statement st = con.createStatement();
            String checkstnumber = "SELECT * FROM STUDENTS WHERE STUDENTNUMBER = '" + stnum.getText() + "'";
            ResultSet re = st.executeQuery(checkstnumber);
            if (re.next()) {
                String getdays = "SELECT DAYSPRESENT FROM STUDENTS WHERE STUDENTNUMBER = '" + stnum.getText() + "'";
                ResultSet results = st.executeQuery(getdays);

                if (results.next()) {
                    int t = results.getInt(1);
                    t += 1;

                    String setdays = "UPDATE STUDENTS SET DAYSPRESENT = '" + t + "' WHERE STUDENTNUMBER = '" + stnum.getText() + "'";

                    String s = Integer.toString(t);
                    counterField.setText(s);
                    st.execute(setdays);

                    String daysabs = "SELECT DAYSPRESENT FROM STUDENTS WHERE STUDENTNUMBER = '" + stnum.getText() + "'";
                    ResultSet days = st.executeQuery(daysabs);
                    if (days.next()) {
                        int ab = 120 - days.getInt(1);
                        String absent = "UPDATE STUDENTS SET DAYSABSENT = '" + ab + "'WHERE STUDENTNUMBER = '" + stnum.getText() + "'";
                        st.execute(absent);
                        
                        if((t/120)*100 < 50){
                            warningField.setBackground(Color.red);
                        }else{
                            warningField.setText("You are good");
                        }
                    }
                    JOptionPane.showMessageDialog(this, "one day added");
                    warningField.setBackground(Color.LIGHT_GRAY);
                    warningField.setText(null);
                }

                stnum.setText(null);
                //counterField.setText(null);
            } else {
                JOptionPane.showMessageDialog(this, "student number\n   not found");
            }
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this, ex.toString());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void counterFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_counterFieldMouseClicked
        counterField.setEditable(false);


    }//GEN-LAST:event_counterFieldMouseClicked

    private void counterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counterFieldActionPerformed

    }//GEN-LAST:event_counterFieldActionPerformed

    private void stnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stnumActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
    jButton1.setBackground(Color.cyan);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
    jButton1.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton1MouseExited

    private void okButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseEntered
   okButton.setBackground(Color.CYAN);
    }//GEN-LAST:event_okButtonMouseEntered

    private void okButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseExited
  okButton.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_okButtonMouseExited

    private void okButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButton1MouseEntered
  okButton1.setBackground(Color.CYAN);
    }//GEN-LAST:event_okButton1MouseEntered

    private void okButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButton1MouseExited
     okButton1.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_okButton1MouseExited
    public JFrame frame;
    private void okButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton1ActionPerformed
    frame = new JFrame("Exit");
       if(JOptionPane.showConfirmDialog(this, "                 EXIT  ?", "Confirm",JOptionPane.YES_NO_OPTION) 
               == JOptionPane.YES_NO_OPTION){
          System.exit(0);
       }
    }//GEN-LAST:event_okButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField counterField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton okButton;
    private javax.swing.JButton okButton1;
    private javax.swing.JTextField stnum;
    private javax.swing.JTextField warningField;
    // End of variables declaration//GEN-END:variables
}
